### ISSUE TITLE
Feature request: throw an error if params are missing

### ISSUE THREAD

**Issue by rottmann** [drewjbartlett/routegen#4]
...

**Comment by drewjbartlett** [comment]
You mean if I declare a route with params and then try to generate without params?

**Comment by rottmann** [comment]
Yes exactly.

**Comment by drewjbartlett** [comment]
@rottmann -- I need to update the docs, but you can now pass params in to append as query params. So I won't be throwing an error. See https://github.com/drewjbartlett/routegen/pull/5
